### ISSUE TITLE
Running RingPotential Example

### ISSUE THREAD

**Issue by salotz** [ADicksonLab/WESTPA-WExplore#2]
Trying to get this up and running. I can get past the `init.sh` part but when I run `run.sh` I get this in the log:

```
System is being built only off of the system driver
Traceback (most recent call last):
  File "/home/salotz/anaconda3/envs/westpa-2017.10/westpa-2017.10/lib/cmds/w_run.py", line 58, in <module>
    sim_manager.load_plugins()
  File "/home/salotz/anaconda3/envs/westpa-2017.10/westpa-2017.10/src/west/sim_manager.py", line 146, in load_plugins
    plugin = extloader.get_object(plugin_name)(self, plugin_config)
  File "/home/salotz/anaconda3/envs/westpa-2017.10/westpa-2017.10/lib/west_tools/westpa/extloader.py", line 78, in get_object
    module = load_module(modspec, path)
  File "/home/salotz/anaconda3/envs/westpa-2017.10/westpa-2017.10/lib/west_tools/westpa/extloader.py", line 45, in load_module
    (fp, pathname, desc) = imp.find_module(next_component, path)
ImportError: No module named wex_plugin

```

**Comment by salotz** [comment]
Pulled the trigger on that issue too fast. Sorry all. Just a `WEST_PYTHONPATH` typo.
